
version: 2.1

executors:
  python-executor:
    working_directory: ~/code
    machine:
      docker_layer_caching: false
      image: "circleci/classic:201808-01"

commands:
  save-eggs-cache:
    description: "Save the .eggs directory after tests"
    steps:
      - save_cache:
          key: v1-test-eggs-cache-{{ checksum "requirements.txt" }}-{{ checksum "test_requirements.txt" }}
          paths:
            - ~/code/.eggs
  restore-eggs-cache:
    description: "Load .eggs cache"
    steps:
      - restore_cache:
          keys:
            - v1-test-eggs-cache-{{ checksum "requirements.txt" }}-{{ checksum "test_requirements.txt" }}
  save-venv-cache:
    description: "Save the virtualenv"
    steps:
      - save_cache:
          key: v1-cache-{{ checksum "requirements.txt" }}-{{ checksum "test_requirements.txt" }}
          paths:
            - ~/code/venv
  restore-venv-cache:
    description: "Restore the virtualenv"
    steps:
      - restore_cache:
          keys:
            - v1-cache-{{ checksum "requirements.txt" }}-{{ checksum "test_requirements.txt" }}

  # Run a single setup.py test<target>, and save the coverage report
  test:
    parameters:
      for:
        description: "Name of test"
        type: string
        default: all
    steps:
      - run: python setup.py test<< parameters.for >>
      - run:
          name: Move coverage report to workspace
          command: |
            mkdir -p /tmp/coverage-reports
            mv ./coverage.xml /tmp/coverage-reports/<< parameters.for >>-coverage.xml
      - run:
          name: Rename junit report to << parameters.for >>-junit.xml
          command: |
            mv ./junit/junit.xml ./junit/<< parameters.for >>-junit.xml

  # Run a collection of 'test' commands
  test-batch:
    parameters:
      tests:
        description: "Run a group of tests, using the 'test' command"
        type: steps
        default:
          - test:
              for: all
    steps:
      - checkout
      - restore-venv-cache
      - restore-eggs-cache
      - run: |
          echo "source ~/code/venv/bin/activate" >> $BASH_ENV
          source ~/code/venv/bin/activate
      - run: |
          which python
          python --version
      - steps: << parameters.tests >>
      - persist_to_workspace:
          root: /tmp/coverage-reports
          paths:
            - ./*-coverage.xml
      - store_test_results:
          path: ./junit/
      - save-eggs-cache
  upload-coverage-reports:
    description: "Upload the coverage reports"
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/coverage-reports
      - run:
          name: "Upload coverage reports"
          command: |
            cp /tmp/coverage-reports/*.xml .
            bash <(curl -s https://codecov.io/bash)

jobs:

  # Make the docker images this project uses.
  make-images:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Make Images
          command: make images

  # Push images, only when on master and/or tagged commits.
  push-images:
    machine:
      docker_layer_caching: false
    environment:
      GORDO_PROD_MODE: true
      DOCKER_REGISTRY: docker.io
      DOCKER_REPO: equinor
    steps:
      - checkout
      - run:
          name: Push Images
          command: |
            make push-server
            make push-client
            make push-builder
            make push-watchman
            make push-workflow-generator

  # Publish to PyPi, only on tagged commits.
  publish-to-pypi:
    executor: python-executor
    steps:
      - checkout
      - restore-venv-cache
      - run:
          name: Build
          command: |
            source ~/code/venv/bin/activate
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          # Requires TWINE_PASSWORD to be set.
          name: Publish
          command: |
            source ~/code/venv/bin/activate
            python -m pip install twine
            twine upload -u statoil-travis --skip-existing dist/*

  # Make the Sphinx documentation for the project; without errors or warnings.
  make-docs:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - python-docs-cache-{{ checksum "requirements.txt" }}-{{ checksum "dev_requirements.txt"}}
      - run:
          name: Install Dependencies
          command: |
            python -m venv ~/venv
            source ~/venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r dev_requirements.txt
      - save_cache:
          key: python-docs-cache-{{ checksum "requirements.txt" }}-{{ checksum "dev_requirements.txt"}}
          paths:
            - ~/venv
      - run:
          name: Make Documentation
          command: |
            source ~/venv/bin/activate
            make docs

  # Install step, before any tests are run to create the cache
  install:
    executor: python-executor
    steps:
      - checkout
      - restore-venv-cache
      - run:
          name: Set Python Version
          command: |
            pyenv versions
            pyenv global 3.6.5
            pyenv versions
      - run:
          name: Virtual Environment
          command: |
            python -m venv ~/code/venv
            echo "source ~/code/venv/bin/activate" >> $BASH_ENV
      - run: pip install --upgrade pip
      - run:
          name: Install Requirements
          command: |
            echo $(which python)
            pip install -r requirements.txt
      - run:
          name: Test Requirements
          command: |
            echo $(which python)
            pip install -r test_requirements.txt
      - save-venv-cache

  # Specific collections of python tests
  test-builder-server-formatting-serializer-watchman-dataset:
    executor: python-executor
    steps:
      - test-batch:
          tests:
            - test:
                for: builder
            - test:
                for: server
            - test:
                for: formatting
            - test:
                for: serializer
            - test:
                for: watchman
            - test:
                for: dataset
  test-client-allelse-dataprovider-util:
    executor: python-executor
    steps:
      - test-batch:
          tests:
            - test:
                for: client
            - test:
                for: allelse
            - test:
                for: dataprovider
            - test:
                for: util
  test-workflow-cli:
    executor: python-executor
    steps:
      - test-batch:
          tests:
            - test:
                for: workflow
            - test:
                for: cli
  test-model:
    executor: python-executor
    steps:
      - test-batch:
          tests:
            - test:
                for: model

  upload-coverage-reports:
    executor: python-executor
    steps:
      - upload-coverage-reports

workflows:
  version: 2.1

  # Run all tests, ensure images and docs can be built
  test:
    jobs:
      - make-docs
      - install
      - test-builder-server-formatting-serializer-watchman-dataset:
          requires:
            - install
      - test-client-allelse-dataprovider-util:
          requires:
            - install
      - test-workflow-cli:
          requires:
            - install
      - test-model:
          requires:
            - install
      - make-images:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - upload-coverage-reports:
          requires:
            - test-builder-server-formatting-serializer-watchman-dataset
            - test-client-allelse-dataprovider-util
            - test-workflow-cli
            - test-model
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - push-images:
          requires:
            - make-images
            - upload-coverage-reports
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
      - publish-to-pypi:
          requires:
            - push-images
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
